version: '3.8'

services:
    mool_dwar:
        build:
            context: ./mool_dwar
        image: bookshare/mool_dwar
        container_name: bookshare_mool_dwar
        volumes:
            - ./mool_dwar/:/app/mool_dwar/
            - /app/mool_dwar/node_modules
        environment:
            - AUTH_HOST=auth
            - AUTH_PORT=${AUTH_PORT}

            - STORE_HOST=store
            - STORE_PORT=${STORE_PORT}
        ports:
            - ${PORT}:${PORT}
        networks:
            - bookshare-net
        links:
            - redis

    redis:
        image: redis:7-alpine
        container_name: bookshare_redis
        volumes:
            - bookshare_redis_00:/data

        expose:
            - ${REDIS_PORT}

        networks:
            - bookshare-net

    auth-db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_USER=${AUTH_POSTGRES_USER}
            - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
            - POSTGRES_DB=${AUTH_POSTGRES_DB}
        volumes:
            - bookshare_postgres_auth_00:/var/lib/postgresql/data/

        expose:
            - ${AUTH_POSTGRES_PORT}

        networks:
            - bookshare-net
    
    store-db:
        image: postgres:14-alpine
        command: -p ${STORE_POSTGRES_PORT}
        environment:
            - POSTGRES_USER=${STORE_POSTGRES_USER}
            - POSTGRES_PASSWORD=${STORE_POSTGRES_PASSWORD}
            - POSTGRES_DB=${STORE_POSTGRES_DB}
        volumes:
            - bookshare_postgres_store_00:/var/lib/postgresql/data/

        expose:
            - ${STORE_POSTGRES_PORT}

        networks:
            - bookshare-net

    test_server:
        build:
            context: ./test_server
        image: bookshare/test_server
        container_name: bookshare_test_server
        volumes:
            - ./test_server/:/app/test_server/
            - /app/test_server/node_modules

        expose:
            - 4001

        networks:
            - bookshare-net

    auth:
        build:
            context: ./auth0
        image: bookshare/auth0
        container_name: bookshare_auth0
        volumes:
            - ./auth0:/app/auth0
        expose:
            - ${AUTH_PORT}
        command: 'python manage.py runserver 0.0.0.0:${AUTH_PORT}'

        environment:
            - POSTGRES_USER=${AUTH_POSTGRES_USER}
            - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
            - POSTGRES_DB=${AUTH_POSTGRES_DB}
            - POSTGRES_PORT=${AUTH_POSTGRES_PORT}
            - POSTGRES_HOST=auth-db

            - REDIS_HOST=redis
            - REDIS_PORT=${REDIS_PORT}

            - RABBIT_MQ_HOST=bookshare_mq

        depends_on:
            - auth-db
            - redis
            - bookshare_mq

        networks:
            - bookshare-net

    store:
        build:
            context: ./store
        image: bookshare/store
        container_name: bookshare_store
        volumes:
            - ./store:/app/store
        expose:
            - ${STORE_PORT}
        command: 'python manage.py runserver 0.0.0.0:${STORE_PORT}'

        environment:
            - POSTGRES_USER=${STORE_POSTGRES_USER}
            - POSTGRES_PASSWORD=${STORE_POSTGRES_PASSWORD}
            - POSTGRES_DB=${STORE_POSTGRES_DB}
            - POSTGRES_PORT=${STORE_POSTGRES_PORT}
            - POSTGRES_HOST=store-db

            - REDIS_HOST=redis
            - REDIS_PORT=${REDIS_PORT}

            - RABBIT_MQ_HOST=bookshare_mq

        depends_on:
            - store-db
            - redis
            - bookshare_mq

        networks:
            - bookshare-net

    bookshare_mq:
        image: rabbitmq:3.11-management-alpine
        container_name: bookshare_rmq
        environment:
            - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq.conf
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - 5672
        volumes:
            - ./rabbit_mq/data:/var/lib/rabbitmq/
            - ./rabbit_mq/logs:/var/log/rabbitmq/
            - ./rabbit_mq/config:/etc/rabbitmq/rabbitmq.conf
        networks:
            - bookshare-net
volumes:
    rabbit_mq_data_00:
    rabbit_mq_logs_00:
    bookshare_postgres_store_00:
    bookshare_postgres_auth_00:
    bookshare_redis_00:

networks:
    bookshare-net:
        name: bookshare-net
        driver: bridge
