version: '3.9'

services:
  mool_dwar:
    build: 
      context: ./mool_dwar
    image: bookshare/mool_dwar
    container_name: bookshare_mool_dwar
    volumes:
      - ./mool_dwar/:/app/mool_dwar/
      - /app/mool_dwar/node_modules
    ports: 
      - 4000:4000
    networks:
      - bookshare-net
    links: 
      - redis

  redis: 
    image: redis:7-alpine
    container_name: bookshare_redis
    volumes:
      - bookshare-redis:/data

    expose:
      - ${REDIS_PORT}

    networks:
      - bookshare-net

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - bookshare-postgres:/var/lib/postgresql/data/
    
    expose:
      - ${POSTGRES_PORT}

    networks:
      - bookshare-net
  
  test_server: 
    build:
      context: ./test_server
    image: bookshare/test_server
    container_name: bookshare_test_server
    volumes:
      - ./test_server/:/app/test_server/
      - /app/test_server/node_modules
    
    expose:
      - 4001
    
    networks:
      - bookshare-net

  auth: 
    build: 
      context: ./auth
    image: bookshare/auth
    container_name: bookshare_auth
    volumes: 
      - ./auth:/app/auth
    expose:
      - ${AUTH_PORT}
    command: "python manage.py runserver 0.0.0.0:${AUTH_PORT}"

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=db

      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}

    depends_on:
      - db
      - redis

    networks:
      - bookshare-net

volumes:
  bookshare-postgres:
    name: bookshare_postgres
  bookshare-redis: 
    name: bookshare_redis

networks:
  bookshare-net:
    name: bookshare-net
    driver: bridge
